---
name: Grafana Image Renderer
version: "1.0.0"
slug: grafana_image_renderer
description: A backend rendering service for Grafana that renders panels and dashboards as PNG images using a headless Chromium browser.
url: https://github.com/cz-lucas/homeassistant-addons
init: false
arch:
  - amd64
  - aarch64
ports:
  8081/tcp: 8081
ports_description:
  8081/tcp: Renderer HTTP API
map:
  - data:rw
options:
  log_level: info
  auth_token: "-"
  ignore_https_errors: false
schema:
  log_level: list(trace|debug|info|warning|error)
  auth_token: str
  ignore_https_errors: bool
